# Generated by Django 5.1.6 on 2025-05-15 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BillingReceipt',
            fields=[
                ('billing_receipt_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('sales_invoice_id', models.CharField(blank=True, max_length=255, null=True)),
                ('service_billing_id', models.CharField(blank=True, max_length=255, null=True)),
                ('total_receipt', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'billing_receipt',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Carrier',
            fields=[
                ('carrier_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('carrier_name', models.CharField(max_length=255)),
                ('service_type', models.TextField(blank=True, null=True)),
                ('carrier_count', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'carrier',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('customer_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('gl_account_id', models.CharField(blank=True, max_length=255, null=True)),
                ('partner_id', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_person', models.CharField(blank=True, max_length=255, null=True)),
                ('email_address', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('address_line1', models.CharField(blank=True, max_length=255, null=True)),
                ('address_line2', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=20, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('customer_type', models.TextField(blank=True, null=True)),
                ('status', models.TextField(blank=True, null=True)),
                ('debt', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'customers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DeliveryReceipt',
            fields=[
                ('delivery_receipt_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('delivery_date', models.DateField(blank=True, null=True)),
                ('received_by', models.CharField(blank=True, max_length=255, null=True)),
                ('signature', models.TextField(blank=True, null=True)),
                ('receipt_status', models.TextField(blank=True, null=True)),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('receiving_module', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'delivery_receipt',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FailedShipment',
            fields=[
                ('failed_shipment_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('failure_date', models.DateField(blank=True, null=True)),
                ('failure_reason', models.TextField()),
                ('resolution_status', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'failed_shipment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GoodsIssue',
            fields=[
                ('goods_issue_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('issued_by', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'goods_issue',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OperationalCost',
            fields=[
                ('operational_cost_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('additional_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_operational_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'operational_cost',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ShipmentDetails',
            fields=[
                ('shipment_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('shipment_date', models.DateField(blank=True, null=True)),
                ('shipment_status', models.TextField(blank=True, null=True)),
                ('tracking_number', models.CharField(max_length=100)),
                ('estimated_arrival_date', models.DateTimeField(blank=True, null=True)),
                ('actual_arrival_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'shipment_details',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ShippingCost',
            fields=[
                ('shipping_cost_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('cost_per_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cost_per_km', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('distance_km', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_shipping_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'shipping_cost',
                'managed': False,
            },
        ),
    ]
