# Generated by Django 5.1.6 on 2025-05-15 07:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PickingList',
            fields=[
                ('picking_list_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('warehouse_id', models.CharField(blank=True, max_length=255, null=True)),
                ('picked_by', models.CharField(blank=True, max_length=255, null=True)),
                ('picked_status', models.TextField(blank=True, null=True)),
                ('picked_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'picking_list',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PickingItem',
            fields=[
                ('picking_item_id', models.AutoField(primary_key=True, serialize=False)),
                ('inventory_item_id', models.CharField(max_length=255)),
                ('item_name', models.CharField(blank=True, max_length=255, null=True)),
                ('item_no', models.CharField(blank=True, max_length=255, null=True)),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('quantity_picked', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('warehouse_id', models.CharField(blank=True, max_length=255, null=True)),
                ('warehouse_name', models.CharField(blank=True, max_length=255, null=True)),
                ('is_picked', models.BooleanField(default=False)),
                ('picked_at', models.DateTimeField(blank=True, null=True)),
                ('picked_by', models.CharField(blank=True, max_length=255, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('delivery_note_id', models.CharField(blank=True, max_length=255, null=True)),
                ('picking_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='picking_items', to='picking.pickinglist')),
            ],
            options={
                'db_table': 'picking_item',
            },
        ),
    ]
