# Generated by Django 5.1.6 on 2025-05-05 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picking', '0002_pickingitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='pickingitem',
            name='delivery_note_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
